eth:
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_IDENTIFIER') }}"
      database: dbt_db
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: compute_wh
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_IDENTIFIER') }}"
      database: prod_db
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: prod_schema
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: compute_wh
    ci:
      account: "{{ env_var('DBT_SNOWFLAKE_IDENTIFIER') }}"
      database: CI_db
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: compute_wh
  target: ci
