// Module: Developing dbt models
QuizBank.add([
  {
    id: "models-001",
    module: "models",
    topic: "Materializations",
    topic_fr: "Matérialisations",
    question: "What is the default materialization of a dbt model when nothing is configured in `dbt_project.yml` or in the model?",
    choices: ["table", "view", "incremental", "ephemeral"],
    answer: [1],
    explanation: "By default, dbt materializes models as **views**. It is the cheapest option: no data is copied and the view always reflects the source. Switch to `table` or `incremental` when read performance requires it.",
    source: "https://docs.getdbt.com/docs/build/materializations",
    fr: {
      question: "Quelle est la matérialisation par défaut d'un modèle dbt si rien n'est configuré dans `dbt_project.yml` ni dans le modèle ?",
      choices: ["table", "view", "incremental", "ephemeral"],
      explanation: "Par défaut, dbt matérialise les modèles en **view**. C'est le choix le moins coûteux : aucune donnée n'est copiée et la vue reflète toujours la source. On passe en `table` ou `incremental` quand la performance de lecture l'exige.",
    },
  },
  {
    id: "models-002",
    module: "models",
    topic: "Materializations",
    topic_fr: "Matérialisations",
    question: "What characterizes a model materialized as `ephemeral`?",
    choices: [
      "It is created as a temporary table dropped at the end of the run",
      "It is not created in the warehouse: its SQL is injected as a CTE into the models that reference it",
      "It is created as a view and then dropped by `dbt clean`",
      "It is only written to `target/compiled` and never executed",
    ],
    answer: [1],
    explanation: "An `ephemeral` model does not exist in the warehouse. dbt interpolates it as a CTE (`with … as (…)`) into every downstream model that `ref()`s it. Consequences: you cannot `select` from it directly in the warehouse, you cannot test it, and debugging is harder.",
    source: "https://docs.getdbt.com/docs/build/materializations#ephemeral",
    fr: {
      question: "Qu'est-ce qui caractérise un modèle matérialisé en `ephemeral` ?",
      choices: [
        "Il est créé comme table temporaire supprimée à la fin du run",
        "Il n'est pas créé dans l'entrepôt : son SQL est injecté en CTE dans les modèles qui le référencent",
        "Il est créé comme vue puis supprimé par `dbt clean`",
        "Il est stocké uniquement dans `target/compiled` et jamais exécuté",
      ],
      explanation: "Un modèle `ephemeral` n'existe pas dans l'entrepôt. dbt l'interpole comme une CTE (`with … as (…)`) dans chaque modèle aval qui fait `ref()` dessus. Conséquences : pas de `select` direct possible dessus dans l'entrepôt, pas de tests possibles dessus, et un débogage plus difficile.",
    },
  },
  {
    id: "models-003",
    module: "models",
    topic: "Incremental models",
    topic_fr: "Modèles incrémentaux",
    question: "When does the `is_incremental()` macro return `True`? (several conditions must all hold — pick the complete answer)",
    choices: [
      "As soon as the model is configured with `materialized='incremental'`",
      "When the model is incremental, the relation already exists in the warehouse, and the run is not launched with `--full-refresh`",
      "When the target table contains at least one row",
      "Only during the first run of the model",
    ],
    answer: [1],
    explanation: "`is_incremental()` is true only if: (1) the model is `incremental`, (2) the relation already exists in the warehouse (not the first run), (3) the `--full-refresh` flag is not passed. Otherwise dbt rebuilds the table from scratch.",
    source: "https://docs.getdbt.com/docs/build/incremental-models",
    fr: {
      question: "Dans quel cas la macro `is_incremental()` renvoie-t-elle `True` ? (plusieurs conditions doivent être réunies — choisissez la réponse complète)",
      choices: [
        "Dès que le modèle est configuré `materialized='incremental'`",
        "Quand le modèle est incrémental, que la relation existe déjà dans l'entrepôt, et que le run n'est pas lancé avec `--full-refresh`",
        "Quand la table cible contient au moins une ligne",
        "Uniquement lors du premier run du modèle",
      ],
      explanation: "`is_incremental()` est vrai seulement si : (1) le modèle est `incremental`, (2) la relation existe déjà dans l'entrepôt (pas le premier run), (3) le flag `--full-refresh` n'est pas passé. Sinon dbt reconstruit la table entièrement.",
    },
  },
  {
    id: "models-004",
    module: "models",
    topic: "Incremental models",
    topic_fr: "Modèles incrémentaux",
    question: "What is the default value of the `on_schema_change` config for an incremental model?",
    choices: ["fail", "append_new_columns", "sync_all_columns", "ignore"],
    answer: [3],
    explanation: "The default is `on_schema_change: ignore`: new columns in the query are not added to the existing table (and removed columns stay). Other values: `fail` stops the run, `append_new_columns` adds new columns, `sync_all_columns` adds and removes columns.",
    source: "https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change",
    fr: {
      question: "Quelle est la valeur par défaut de la config `on_schema_change` d'un modèle incrémental ?",
      choices: ["fail", "append_new_columns", "sync_all_columns", "ignore"],
      explanation: "Par défaut `on_schema_change: ignore` : les nouvelles colonnes de la requête ne sont pas ajoutées à la table existante (et les colonnes supprimées restent). Les autres valeurs : `fail` stoppe le run, `append_new_columns` ajoute les nouvelles colonnes, `sync_all_columns` ajoute et supprime.",
    },
  },
  {
    id: "models-005",
    module: "models",
    topic: "Incremental models",
    topic_fr: "Modèles incrémentaux",
    question: "In an incremental model, what does `{{ this }}` refer to?",
    choices: [
      "The source model referenced through `source()`",
      "The relation (database.schema.table) of the current model in the warehouse",
      "The SQL file currently being compiled",
      "The last model executed in the DAG",
    ],
    answer: [1],
    explanation: "`{{ this }}` is the `Relation` of the current model as it exists in the warehouse. It enables the classic pattern: `where updated_at > (select max(updated_at) from {{ this }})`.",
    source: "https://docs.getdbt.com/reference/dbt-jinja-functions/this",
    fr: {
      question: "Dans un modèle incrémental, à quoi fait référence `{{ this }}` ?",
      choices: [
        "Au modèle source référencé via `source()`",
        "À la relation (database.schema.table) du modèle en cours dans l'entrepôt",
        "Au fichier SQL en cours de compilation",
        "Au dernier modèle exécuté dans le DAG",
      ],
      explanation: "`{{ this }}` est la `Relation` du modèle courant tel qu'il existe dans l'entrepôt. C'est ce qui permet le pattern classique : `where updated_at > (select max(updated_at) from {{ this }})`.",
    },
  },
  {
    id: "models-006",
    module: "models",
    topic: "Incremental models",
    topic_fr: "Modèles incrémentaux",
    question: "Which configs are **required** to use the `microbatch` incremental strategy? (choose 3)",
    choices: ["event_time", "begin", "unique_key", "batch_size", "lookback"],
    answer: [0, 1, 3],
    explanation: "`microbatch` needs `event_time` (timestamp column of the model), `begin` (start date for the first build) and `batch_size` (`hour`, `day`, `month`, `year`). `lookback` is optional (default 1) and `unique_key` is not required: each batch does a delete+insert on its time window.",
    source: "https://docs.getdbt.com/docs/build/incremental-microbatch",
    fr: {
      question: "Quelles configurations sont **obligatoires** pour utiliser la stratégie `microbatch` ? (3 réponses)",
      choices: ["event_time", "begin", "unique_key", "batch_size", "lookback"],
      explanation: "`microbatch` a besoin de `event_time` (colonne d'horodatage du modèle), `begin` (date de départ pour le premier build) et `batch_size` (`hour`, `day`, `month`, `year`). `lookback` est optionnel (défaut 1) et `unique_key` n'est pas requis : chaque batch fait un delete+insert sur sa fenêtre temporelle.",
    },
  },
  {
    id: "models-007",
    module: "models",
    topic: "Incremental models",
    topic_fr: "Modèles incrémentaux",
    question: "Which incremental strategy is used by default on Snowflake when `incremental_strategy` is not set?",
    choices: ["append", "merge", "delete+insert", "insert_overwrite"],
    answer: [1],
    explanation: "On Snowflake (as on BigQuery and Databricks), the default strategy is `merge`. Without a `unique_key`, the `merge` behaves like an `append`. `delete+insert` and `append` are also available; `insert_overwrite` is not supported on Snowflake.",
    source: "https://docs.getdbt.com/docs/build/incremental-strategy",
    fr: {
      question: "Quelle stratégie incrémentale est utilisée par défaut sur Snowflake si `incremental_strategy` n'est pas précisé ?",
      choices: ["append", "merge", "delete+insert", "insert_overwrite"],
      explanation: "Sur Snowflake (comme BigQuery et Databricks), la stratégie par défaut est `merge`. Sans `unique_key`, le `merge` se comporte comme un `append`. `delete+insert` et `append` sont aussi disponibles ; `insert_overwrite` n'est pas supporté sur Snowflake.",
    },
  },
  {
    id: "models-008",
    module: "models",
    topic: "Jinja & macros",
    topic_fr: "Jinja & macros",
    question: "Why is a `run_query()` call usually wrapped in an `{% if execute %}` block?",
    choices: [
      "Because `run_query` is only available in `execute` mode",
      "Because at parse time dbt does not run SQL: `execute` is `False` and the result would be `None`, which breaks code that uses it",
      "To avoid running the query twice",
      "Because `execute` enables query logging",
    ],
    answer: [1],
    explanation: "dbt first parses the project to build the DAG. During that phase `execute` is `False` and queries are not sent to the warehouse: `run_query` returns `None`. Any code doing `.columns[0].values()` on the result would crash — hence the `{% if execute %}` guard.",
    source: "https://docs.getdbt.com/reference/dbt-jinja-functions/execute",
    fr: {
      question: "Pourquoi entoure-t-on souvent un appel `run_query()` d'un bloc `{% if execute %}` ?",
      choices: [
        "Parce que `run_query` n'est disponible qu'en mode `execute`",
        "Parce qu'au moment du parsing, dbt n'exécute pas de SQL : `execute` vaut `False` et le résultat serait `None`, ce qui casse le code qui l'exploite",
        "Pour éviter d'exécuter la requête deux fois",
        "Parce que `execute` active les logs de la requête",
      ],
      explanation: "dbt parse le projet une première fois pour construire le DAG. Pendant cette phase, `execute` vaut `False` et les requêtes ne sont pas envoyées à l'entrepôt : `run_query` renvoie `None`. Tout code qui fait `.columns[0].values()` sur le résultat planterait — d'où le garde-fou `{% if execute %}`.",
    },
  },
  {
    id: "models-009",
    module: "models",
    topic: "Jinja & macros",
    topic_fr: "Jinja & macros",
    question: "What is the difference between `{% … %}` and `{{ … }}` in Jinja?",
    choices: [
      "`{% %}` is for comments, `{{ }}` for code",
      "`{% %}` runs statements (if, for, set, macro) without printing anything; `{{ }}` evaluates an expression and inserts the result into the SQL",
      "They are interchangeable",
      "`{{ }}` is only valid inside macros",
    ],
    answer: [1],
    explanation: "`{% %}` = statements (control flow, assignments, macro definitions): nothing is written to the compiled SQL. `{{ }}` = expressions: the value is rendered into the SQL. Jinja comments are written `{# … #}`.",
    source: "https://docs.getdbt.com/docs/build/jinja-macros",
    fr: {
      question: "Quelle est la différence entre `{% … %}` et `{{ … }}` en Jinja ?",
      choices: [
        "`{% %}` est pour les commentaires, `{{ }}` pour le code",
        "`{% %}` exécute des instructions (if, for, set, macro) sans rien afficher ; `{{ }}` évalue une expression et insère le résultat dans le SQL",
        "Ils sont interchangeables",
        "`{{ }}` n'est valide que dans les macros",
      ],
      explanation: "`{% %}` = statements (contrôle de flux, affectations, définition de macros) : rien n'est écrit dans le SQL compilé. `{{ }}` = expressions : la valeur est rendue dans le SQL. Les commentaires Jinja s'écrivent `{# … #}`.",
    },
  },
  {
    id: "models-010",
    module: "models",
    topic: "Variables",
    topic_fr: "Variables",
    question: "A variable `start_date` is defined in `dbt_project.yml` (`vars:`) AND passed on the command line with `--vars '{start_date: 2024-01-01}'`. Which value is used?",
    choices: [
      "The one from `dbt_project.yml`, project config takes precedence",
      "The one from the command line, it overrides the project config",
      "dbt raises a conflict error",
      "The first one encountered during parsing",
    ],
    answer: [1],
    explanation: "Precedence of `vars`: command line (`--vars`) > `vars` scoped to the project/package in `dbt_project.yml` > global `vars` in `dbt_project.yml` > default value in `var('x', default)`.",
    source: "https://docs.getdbt.com/docs/build/project-variables#variable-precedence",
    fr: {
      question: "Une variable `start_date` est définie dans `dbt_project.yml` (`vars:`) ET passée en ligne de commande avec `--vars '{start_date: 2024-01-01}'`. Quelle valeur est utilisée ?",
      choices: [
        "Celle de `dbt_project.yml`, la config projet est prioritaire",
        "Celle de la ligne de commande, elle écrase la config projet",
        "dbt lève une erreur de conflit",
        "La première rencontrée lors du parsing",
      ],
      explanation: "Ordre de priorité des `vars` : ligne de commande (`--vars`) > `vars` scoped au projet/package dans `dbt_project.yml` > `vars` globales dans `dbt_project.yml` > valeur par défaut dans `var('x', default)`.",
    },
  },
  {
    id: "models-011",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "Which metadata columns does a snapshot add to the target table? (choose 4)",
    choices: ["dbt_scd_id", "dbt_updated_at", "dbt_valid_from", "dbt_valid_to", "dbt_row_hash", "dbt_loaded_at"],
    answer: [0, 1, 2, 3],
    explanation: "A snapshot (SCD type 2) adds `dbt_scd_id` (unique key of the version), `dbt_updated_at`, `dbt_valid_from` and `dbt_valid_to` (`null` for the current version, unless `dbt_valid_to_current` is configured). With `hard_deletes: new_record` (dbt 1.9+), a `dbt_is_deleted` column is added too.",
    source: "https://docs.getdbt.com/docs/build/snapshots",
    fr: {
      question: "Quelles colonnes de métadonnées un snapshot ajoute-t-il à la table cible ? (4 réponses)",
      choices: ["dbt_scd_id", "dbt_updated_at", "dbt_valid_from", "dbt_valid_to", "dbt_row_hash", "dbt_loaded_at"],
      explanation: "Un snapshot (SCD type 2) ajoute `dbt_scd_id` (clé unique de la version), `dbt_updated_at`, `dbt_valid_from` et `dbt_valid_to` (`null` pour la version courante, sauf si `dbt_valid_to_current` est configuré). Avec `hard_deletes: new_record` (dbt 1.9+), une colonne `dbt_is_deleted` s'ajoute.",
    },
  },
  {
    id: "models-012",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "You need to snapshot a table that has no reliable update column (`updated_at`). Which strategy should you choose?",
    choices: [
      "`strategy: timestamp` with `updated_at: current_timestamp()`",
      "`strategy: check` with `check_cols` listing the columns to compare (or `all`)",
      "`strategy: merge` with a `unique_key`",
      "It is impossible to snapshot without a timestamp column",
    ],
    answer: [1],
    explanation: "The `check` strategy compares the values of the columns listed in `check_cols` (or `all`) between the source and the latest snapshotted version. It is more expensive than `timestamp` but works without a reliable update column.",
    source: "https://docs.getdbt.com/docs/build/snapshots#check-strategy",
    fr: {
      question: "Vous devez snapshoter une table sans colonne fiable de mise à jour (`updated_at`). Quelle stratégie choisir ?",
      choices: [
        "`strategy: timestamp` avec `updated_at: current_timestamp()`",
        "`strategy: check` avec `check_cols` listant les colonnes à comparer (ou `all`)",
        "`strategy: merge` avec `unique_key`",
        "Il est impossible de snapshoter sans colonne d'horodatage",
      ],
      explanation: "La stratégie `check` compare les valeurs des colonnes listées dans `check_cols` (ou `all`) entre la source et la dernière version snapshotée. Elle est plus coûteuse que `timestamp` mais fonctionne sans colonne de mise à jour fiable.",
    },
  },
  {
    id: "models-013",
    module: "models",
    topic: "Seeds",
    topic_fr: "Seeds",
    question: "What is an appropriate use case for a seed?",
    choices: [
      "Loading the ERP's daily CSV exports",
      "Storing small, static reference tables versioned with the code (e.g. country list, code mappings)",
      "Loading large data volumes without an ingestion tool",
      "Saving test results",
    ],
    answer: [1],
    explanation: "Seeds are CSV files versioned in the repo and loaded with `dbt seed`. They suit small reference data that rarely changes. They are not meant for large or frequently updated raw data, nor for sensitive data.",
    source: "https://docs.getdbt.com/docs/build/seeds",
    fr: {
      question: "Quel est le cas d'usage approprié pour un seed ?",
      choices: [
        "Charger quotidiennement les exports CSV de l'ERP",
        "Stocker de petites tables de référence statiques versionnées avec le code (ex : liste de pays, mapping de codes)",
        "Charger des données volumineuses sans passer par un outil d'ingestion",
        "Sauvegarder les résultats de tests",
      ],
      explanation: "Les seeds sont des CSV versionnés dans le repo, chargés par `dbt seed`. Ils conviennent aux petites données de référence qui changent rarement. Ils ne sont pas faits pour de la donnée brute volumineuse ou fréquemment mise à jour, ni pour des données sensibles.",
    },
  },
  {
    id: "models-014",
    module: "models",
    topic: "Python models",
    topic_fr: "Modèles Python",
    question: "What signature must the main function of a dbt Python model have?",
    choices: [
      "`def run(dbt, session)` returning a SQL string",
      "`def model(dbt, session)` returning a DataFrame",
      "`def main()` writing to `dbt.target`",
      "`def model(context)` returning a dictionary",
    ],
    answer: [1],
    explanation: "A Python model defines `def model(dbt, session)` and returns a DataFrame (Snowpark, PySpark or pandas depending on the platform). Dependencies are accessed with `dbt.ref('…')` / `dbt.source('…','…')` and config with `dbt.config(...)`. The result can only be materialized as `table` or `incremental`.",
    source: "https://docs.getdbt.com/docs/build/python-models",
    fr: {
      question: "Quelle signature doit avoir la fonction principale d'un modèle Python dbt ?",
      choices: [
        "`def run(dbt, session)` qui renvoie une chaîne SQL",
        "`def model(dbt, session)` qui renvoie un DataFrame",
        "`def main()` qui écrit dans `dbt.target`",
        "`def model(context)` qui renvoie un dictionnaire",
      ],
      explanation: "Un modèle Python définit `def model(dbt, session)` et renvoie un DataFrame (Snowpark, PySpark ou pandas selon la plateforme). On accède aux dépendances via `dbt.ref('…')` / `dbt.source('…','…')` et à la config via `dbt.config(...)`. Le résultat est matérialisé en `table` ou `incremental` seulement.",
    },
  },
  {
    id: "models-015",
    module: "models",
    topic: "Custom schemas",
    topic_fr: "Schémas personnalisés",
    question: "The profile's target schema is `dbt_serge`. A model is configured with `schema: marts`. With the default `generate_schema_name` macro, in which schema is it created?",
    choices: ["marts", "dbt_serge", "dbt_serge_marts", "marts_dbt_serge"],
    answer: [2],
    explanation: "The default behavior concatenates the target schema and the custom schema: `<target_schema>_<custom_schema>` → `dbt_serge_marts`. This prevents several developers from overwriting the same `marts` schema. To use `marts` as-is in prod, override the `generate_schema_name` macro.",
    source: "https://docs.getdbt.com/docs/build/custom-schemas",
    fr: {
      question: "Le schéma cible du profil est `dbt_serge`. Un modèle est configuré avec `schema: marts`. Avec la macro `generate_schema_name` par défaut, dans quel schéma est-il créé ?",
      choices: ["marts", "dbt_serge", "dbt_serge_marts", "marts_dbt_serge"],
      explanation: "Le comportement par défaut concatène le schéma cible et le schéma personnalisé : `<target_schema>_<custom_schema>` → `dbt_serge_marts`. Cela évite que plusieurs développeurs écrasent le même schéma `marts`. Pour utiliser `marts` tel quel en prod, il faut surcharger la macro `generate_schema_name`.",
    },
  },
  {
    id: "models-016",
    module: "models",
    topic: "Hooks & grants",
    topic_fr: "Hooks & grants",
    question: "You want to run a `grant select` on every model right after it is created. Which approach is recommended?",
    choices: [
      "An `on-run-end` hook that loops over all models",
      "The `grants` config on the model (or project), which handles grants natively",
      "A macro called with `dbt run-operation` after each run",
      "A `pre-hook` on the model",
    ],
    answer: [1],
    explanation: "Since dbt 1.2, the `grants:` config (`grants: {select: ['role_bi']}`) manages permissions natively and idempotently, right after materialization. It is preferable to manual `post-hook`s. A `pre-hook` runs before creation, so too early.",
    source: "https://docs.getdbt.com/reference/resource-configs/grants",
    fr: {
      question: "Vous voulez exécuter un `grant select` sur chaque modèle juste après sa création. Quelle approche est recommandée ?",
      choices: [
        "Un `on-run-end` hook qui boucle sur tous les modèles",
        "La config `grants` du modèle (ou du projet), qui gère les grants nativement",
        "Une macro appelée avec `dbt run-operation` après chaque run",
        "Un `pre-hook` sur le modèle",
      ],
      explanation: "Depuis dbt 1.2, la config `grants:` (`grants: {select: ['role_bi']}`) gère les permissions de manière native et idempotente, juste après la matérialisation. C'est préférable aux `post-hook` manuels. Le `pre-hook` s'exécute avant la création, donc trop tôt.",
    },
  },
  {
    id: "models-017",
    module: "models",
    topic: "Project structure",
    topic_fr: "Structure du projet",
    question: "According to dbt best practices, which model layer should do 1:1 column renaming/casting from the source, with no joins?",
    choices: ["marts", "intermediate", "staging", "sources"],
    answer: [2],
    explanation: "The **staging** layer (`stg_`) is a cleaned mirror of the sources: one source = one staging model, renaming, casting, no joins or aggregations. `intermediate` combines and transforms, `marts` exposes the final business entities.",
    source: "https://docs.getdbt.com/best-practices/how-we-structure/1-guide-overview",
    fr: {
      question: "Selon les bonnes pratiques dbt, quelle couche de modèles doit faire du renommage/typage de colonnes 1:1 avec la source, sans jointure ?",
      choices: ["marts", "intermediate", "staging", "sources"],
      explanation: "La couche **staging** (`stg_`) est un miroir nettoyé des sources : une source = un modèle staging, renommage, cast, pas de jointure ni d'agrégation. `intermediate` combine et transforme, `marts` expose les entités métier finales.",
    },
  },
  {
    id: "models-018",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "Which commands execute snapshots? (choose 2)",
    choices: ["dbt run", "dbt snapshot", "dbt build", "dbt seed"],
    answer: [1, 2],
    explanation: "`dbt snapshot` runs snapshots only. `dbt build` runs seeds, snapshots, models and tests in DAG order, so it includes them. `dbt run` executes **models only** — a common trap: a job that only does `dbt run` never updates the snapshot history.",
    source: "https://docs.getdbt.com/reference/commands/snapshot",
    fr: {
      question: "Quelles commandes exécutent les snapshots ? (2 réponses)",
      choices: ["dbt run", "dbt snapshot", "dbt build", "dbt seed"],
      explanation: "`dbt snapshot` exécute uniquement les snapshots. `dbt build` exécute seeds, snapshots, modèles et tests dans l'ordre du DAG, donc les inclut. `dbt run` n'exécute que les **modèles** — piège classique : un job qui ne fait que `dbt run` ne met jamais à jour l'historique du snapshot.",
    },
  },
  {
    id: "models-019",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "Since dbt 1.9, what is the recommended way to define a snapshot?",
    choices: [
      "A `{% snapshot %}` block in a `.sql` file under `snapshots/`",
      "A YAML file under `snapshots/` with a `snapshots:` key, `relation: ref(...)` or `source(...)`, and the config (`unique_key`, `strategy`, …)",
      "A model with `materialized: snapshot`",
      "A `snapshots:` section in `dbt_project.yml` listing the tables",
    ],
    answer: [1],
    explanation: "dbt 1.9 introduced YAML-defined snapshots: `snapshots: - name: orders_snapshot  relation: source('erp','orders')  config: {unique_key: id, strategy: timestamp, updated_at: updated_at}`. The Jinja `{% snapshot %}` block still works but is the legacy syntax. Both are stored in the `snapshots/` path.",
    source: "https://docs.getdbt.com/docs/build/snapshots#configuring-snapshots",
    fr: {
      question: "Depuis dbt 1.9, quelle est la manière recommandée de définir un snapshot ?",
      choices: [
        "Un bloc `{% snapshot %}` dans un fichier `.sql` sous `snapshots/`",
        "Un fichier YAML sous `snapshots/` avec une clé `snapshots:`, `relation: ref(...)` ou `source(...)`, et la config (`unique_key`, `strategy`, …)",
        "Un modèle avec `materialized: snapshot`",
        "Une section `snapshots:` dans `dbt_project.yml` listant les tables",
      ],
      explanation: "dbt 1.9 a introduit les snapshots définis en YAML : `snapshots: - name: orders_snapshot  relation: source('erp','orders')  config: {unique_key: id, strategy: timestamp, updated_at: updated_at}`. Le bloc Jinja `{% snapshot %}` fonctionne toujours mais c'est la syntaxe historique. Les deux vivent dans le dossier `snapshots/`.",
    },
  },
  {
    id: "models-020",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "A row disappears from the source table. With the default snapshot config, what happens to its record in the snapshot table?",
    choices: [
      "The record is deleted from the snapshot",
      "Nothing: the record stays with `dbt_valid_to = null` as if it were still current",
      "`dbt_valid_to` is set to the snapshot time",
      "A new row is inserted with `dbt_is_deleted = True`",
    ],
    answer: [1],
    explanation: "By default `hard_deletes: ignore`: dbt does not track rows deleted from the source, so the record looks current forever. `hard_deletes: invalidate` (formerly `invalidate_hard_deletes: true`) closes the record by setting `dbt_valid_to`. `hard_deletes: new_record` (dbt 1.9+) adds a new row flagged `dbt_is_deleted = True`.",
    source: "https://docs.getdbt.com/reference/resource-configs/hard-deletes",
    fr: {
      question: "Une ligne disparaît de la table source. Avec la config de snapshot par défaut, qu'advient-il de son enregistrement dans la table de snapshot ?",
      choices: [
        "L'enregistrement est supprimé du snapshot",
        "Rien : l'enregistrement reste avec `dbt_valid_to = null` comme s'il était toujours courant",
        "`dbt_valid_to` est positionné à l'heure du snapshot",
        "Une nouvelle ligne est insérée avec `dbt_is_deleted = True`",
      ],
      explanation: "Par défaut `hard_deletes: ignore` : dbt ne suit pas les lignes supprimées de la source, l'enregistrement paraît courant indéfiniment. `hard_deletes: invalidate` (ex-`invalidate_hard_deletes: true`) clôt l'enregistrement en renseignant `dbt_valid_to`. `hard_deletes: new_record` (dbt 1.9+) ajoute une nouvelle ligne marquée `dbt_is_deleted = True`.",
    },
  },
  {
    id: "models-021",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "Which configs are **required** for a snapshot using the `timestamp` strategy? (choose 3)",
    choices: ["unique_key", "strategy", "updated_at", "check_cols", "target_schema"],
    answer: [0, 1, 2],
    explanation: "`timestamp` needs `unique_key` (row identifier), `strategy: timestamp` and `updated_at` (column compared to detect changes). `check_cols` is for the `check` strategy. Since dbt 1.9, `target_schema` is optional: the snapshot lands in the target's schema (with `schema` to customize), whereas it used to be mandatory.",
    source: "https://docs.getdbt.com/docs/build/snapshots#timestamp-strategy-recommended",
    fr: {
      question: "Quelles configs sont **obligatoires** pour un snapshot en stratégie `timestamp` ? (3 réponses)",
      choices: ["unique_key", "strategy", "updated_at", "check_cols", "target_schema"],
      explanation: "`timestamp` exige `unique_key` (identifiant de ligne), `strategy: timestamp` et `updated_at` (colonne comparée pour détecter les changements). `check_cols` sert à la stratégie `check`. Depuis dbt 1.9, `target_schema` est optionnel : le snapshot atterrit dans le schéma de la cible (personnalisable avec `schema`), alors qu'il était obligatoire avant.",
    },
  },
  {
    id: "models-022",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "Why does dbt recommend running snapshots on a dedicated, frequent schedule in production, and **not** re-running them freely in development?",
    choices: [
      "Because snapshots are slow to compile",
      "Because a snapshot table is append-only history: every run may create new versions, and a `--full-refresh` or a dev run against the wrong schema can lose or pollute that history",
      "Because snapshots require `threads: 1`",
      "Because snapshots lock the source table",
    ],
    answer: [1],
    explanation: "A snapshot captures **history that cannot be reconstructed** later. It should run at a frequency matching the granularity you need (often hourly/daily) in a stable environment. Running it in every dev environment is pointless and `--full-refresh` on a snapshot is refused by default (`dbt snapshot` ignores the flag) precisely to protect the history.",
    source: "https://docs.getdbt.com/docs/build/snapshots#snapshot-best-practices",
    fr: {
      question: "Pourquoi dbt recommande-t-il d'exécuter les snapshots sur un planning dédié et fréquent en production, et de **ne pas** les relancer librement en développement ?",
      choices: [
        "Parce que les snapshots sont lents à compiler",
        "Parce qu'une table de snapshot est un historique en ajout seul : chaque run peut créer de nouvelles versions, et un `--full-refresh` ou un run de dev sur le mauvais schéma peut perdre ou polluer cet historique",
        "Parce que les snapshots exigent `threads: 1`",
        "Parce que les snapshots verrouillent la table source",
      ],
      explanation: "Un snapshot capture un **historique impossible à reconstruire** après coup. Il doit tourner à une fréquence correspondant à la granularité voulue (souvent horaire/quotidienne) dans un environnement stable. Le lancer dans chaque environnement de dev est inutile, et `--full-refresh` sur un snapshot est ignoré par défaut par `dbt snapshot`, précisément pour protéger l'historique.",
    },
  },
  {
    id: "models-023",
    module: "models",
    topic: "Snapshots",
    topic_fr: "Snapshots",
    question: "You want to query only the **current** version of each record in a snapshot table. Which filter do you use?",
    choices: [
      "`where dbt_valid_from = max(dbt_valid_from)`",
      "`where dbt_valid_to is null`",
      "`where dbt_updated_at = current_date`",
      "`where dbt_scd_id is not null`",
    ],
    answer: [1],
    explanation: "The current version of a record is the one whose `dbt_valid_to` is `null` (or equals the value of `dbt_valid_to_current` if that config is set, e.g. `9999-12-31`). To see a record as of a date `D`: `where dbt_valid_from <= D and (dbt_valid_to > D or dbt_valid_to is null)`.",
    source: "https://docs.getdbt.com/docs/build/snapshots#how-snapshots-work",
    fr: {
      question: "Vous voulez interroger uniquement la version **courante** de chaque enregistrement d'une table de snapshot. Quel filtre utilisez-vous ?",
      choices: [
        "`where dbt_valid_from = max(dbt_valid_from)`",
        "`where dbt_valid_to is null`",
        "`where dbt_updated_at = current_date`",
        "`where dbt_scd_id is not null`",
      ],
      explanation: "La version courante d'un enregistrement est celle dont `dbt_valid_to` est `null` (ou égale à la valeur de `dbt_valid_to_current` si cette config est définie, ex. `9999-12-31`). Pour voir un enregistrement à une date `D` : `where dbt_valid_from <= D and (dbt_valid_to > D or dbt_valid_to is null)`.",
    },
  },
]);
