// Module : Développer des modèles dbt
QuizBank.add([
  {
    id: "models-001",
    module: "models",
    topic: "Matérialisations",
    question: "Quelle est la matérialisation par défaut d'un modèle dbt si rien n'est configuré dans `dbt_project.yml` ni dans le modèle ?",
    choices: ["table", "view", "incremental", "ephemeral"],
    answer: [1],
    explanation: "Par défaut, dbt matérialise les modèles en **view**. C'est le choix le moins coûteux : aucune donnée n'est copiée et la vue reflète toujours la source. On passe en `table` ou `incremental` quand la performance de lecture l'exige.",
    source: "https://docs.getdbt.com/docs/build/materializations",
  },
  {
    id: "models-002",
    module: "models",
    topic: "Matérialisations",
    question: "Qu'est-ce qui caractérise un modèle matérialisé en `ephemeral` ?",
    choices: [
      "Il est créé comme table temporaire supprimée à la fin du run",
      "Il n'est pas créé dans l'entrepôt : son SQL est injecté en CTE dans les modèles qui le référencent",
      "Il est créé comme vue puis supprimé par `dbt clean`",
      "Il est stocké uniquement dans `target/compiled` et jamais exécuté",
    ],
    answer: [1],
    explanation: "Un modèle `ephemeral` n'existe pas dans l'entrepôt. dbt l'interpole comme une CTE (`with … as (…)`) dans chaque modèle aval qui fait `ref()` dessus. Conséquences : pas de `select` direct possible dessus dans l'entrepôt, pas de tests possibles dessus, et un débogage plus difficile.",
    source: "https://docs.getdbt.com/docs/build/materializations#ephemeral",
  },
  {
    id: "models-003",
    module: "models",
    topic: "Incrémental",
    question: "Dans quel cas la macro `is_incremental()` renvoie-t-elle `True` ? (plusieurs conditions doivent être réunies — choisissez la réponse complète)",
    choices: [
      "Dès que le modèle est configuré `materialized='incremental'`",
      "Quand le modèle est incrémental, que la relation existe déjà dans l'entrepôt, et que le run n'est pas lancé avec `--full-refresh`",
      "Quand la table cible contient au moins une ligne",
      "Uniquement lors du premier run du modèle",
    ],
    answer: [1],
    explanation: "`is_incremental()` est vrai seulement si : (1) le modèle est `incremental`, (2) la relation existe déjà dans l'entrepôt (pas le premier run), (3) le flag `--full-refresh` n'est pas passé. Sinon dbt reconstruit la table entièrement.",
    source: "https://docs.getdbt.com/docs/build/incremental-models",
  },
  {
    id: "models-004",
    module: "models",
    topic: "Incrémental",
    question: "Quelle est la valeur par défaut de la config `on_schema_change` d'un modèle incrémental ?",
    choices: ["fail", "append_new_columns", "sync_all_columns", "ignore"],
    answer: [3],
    explanation: "Par défaut `on_schema_change: ignore` : les nouvelles colonnes de la requête ne sont pas ajoutées à la table existante (et les colonnes supprimées restent). Les autres valeurs : `fail` stoppe le run, `append_new_columns` ajoute les nouvelles colonnes, `sync_all_columns` ajoute et supprime.",
    source: "https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change",
  },
  {
    id: "models-005",
    module: "models",
    topic: "Incrémental",
    question: "Dans un modèle incrémental, à quoi fait référence `{{ this }}` ?",
    choices: [
      "Au modèle source référencé via `source()`",
      "À la relation (database.schema.table) du modèle en cours dans l'entrepôt",
      "Au fichier SQL en cours de compilation",
      "Au dernier modèle exécuté dans le DAG",
    ],
    answer: [1],
    explanation: "`{{ this }}` est la `Relation` du modèle courant tel qu'il existe dans l'entrepôt. C'est ce qui permet le pattern classique : `where updated_at > (select max(updated_at) from {{ this }})`.",
    source: "https://docs.getdbt.com/reference/dbt-jinja-functions/this",
  },
  {
    id: "models-006",
    module: "models",
    topic: "Incrémental",
    question: "Quelles configurations sont **obligatoires** pour utiliser la stratégie `microbatch` ? (3 réponses)",
    choices: ["event_time", "begin", "unique_key", "batch_size", "lookback"],
    answer: [0, 1, 3],
    explanation: "`microbatch` a besoin de `event_time` (colonne d'horodatage du modèle), `begin` (date de départ pour le premier build) et `batch_size` (`hour`, `day`, `month`, `year`). `lookback` est optionnel (défaut 1) et `unique_key` n'est pas requis : chaque batch fait un delete+insert sur sa fenêtre temporelle.",
    source: "https://docs.getdbt.com/docs/build/incremental-microbatch",
  },
  {
    id: "models-007",
    module: "models",
    topic: "Incrémental",
    question: "Quelle stratégie incrémentale est utilisée par défaut sur Snowflake si `incremental_strategy` n'est pas précisé ?",
    choices: ["append", "merge", "delete+insert", "insert_overwrite"],
    answer: [1],
    explanation: "Sur Snowflake (comme BigQuery et Databricks), la stratégie par défaut est `merge`. Sans `unique_key`, le `merge` se comporte comme un `append`. `delete+insert` et `append` sont aussi disponibles ; `insert_overwrite` n'est pas supporté sur Snowflake.",
    source: "https://docs.getdbt.com/docs/build/incremental-strategy",
  },
  {
    id: "models-008",
    module: "models",
    topic: "Jinja & macros",
    question: "Pourquoi entoure-t-on souvent un appel `run_query()` d'un bloc `{% if execute %}` ?",
    choices: [
      "Parce que `run_query` n'est disponible qu'en mode `execute`",
      "Parce qu'au moment du parsing, dbt n'exécute pas de SQL : `execute` vaut `False` et le résultat serait `None`, ce qui casse le code qui l'exploite",
      "Pour éviter d'exécuter la requête deux fois",
      "Parce que `execute` active les logs de la requête",
    ],
    answer: [1],
    explanation: "dbt parse le projet une première fois pour construire le DAG. Pendant cette phase, `execute` vaut `False` et les requêtes ne sont pas envoyées à l'entrepôt : `run_query` renvoie `None`. Tout code qui fait `.columns[0].values()` sur le résultat planterait — d'où le garde-fou `{% if execute %}`.",
    source: "https://docs.getdbt.com/reference/dbt-jinja-functions/execute",
  },
  {
    id: "models-009",
    module: "models",
    topic: "Jinja & macros",
    question: "Quelle est la différence entre `{% … %}` et `{{ … }}` en Jinja ?",
    choices: [
      "`{% %}` est pour les commentaires, `{{ }}` pour le code",
      "`{% %}` exécute des instructions (if, for, set, macro) sans rien afficher ; `{{ }}` évalue une expression et insère le résultat dans le SQL",
      "Ils sont interchangeables",
      "`{{ }}` n'est valide que dans les macros",
    ],
    answer: [1],
    explanation: "`{% %}` = statements (contrôle de flux, affectations, définition de macros) : rien n'est écrit dans le SQL compilé. `{{ }}` = expressions : la valeur est rendue dans le SQL. Les commentaires Jinja s'écrivent `{# … #}`.",
    source: "https://docs.getdbt.com/docs/build/jinja-macros",
  },
  {
    id: "models-010",
    module: "models",
    topic: "Variables",
    question: "Une variable `start_date` est définie dans `dbt_project.yml` (`vars:`) ET passée en ligne de commande avec `--vars '{start_date: 2024-01-01}'`. Quelle valeur est utilisée ?",
    choices: [
      "Celle de `dbt_project.yml`, la config projet est prioritaire",
      "Celle de la ligne de commande, elle écrase la config projet",
      "dbt lève une erreur de conflit",
      "La première rencontrée lors du parsing",
    ],
    answer: [1],
    explanation: "Ordre de priorité des `vars` : ligne de commande (`--vars`) > `vars` scoped au projet/package dans `dbt_project.yml` > `vars` globales dans `dbt_project.yml` > valeur par défaut dans `var('x', default)`.",
    source: "https://docs.getdbt.com/docs/build/project-variables#variable-precedence",
  },
  {
    id: "models-011",
    module: "models",
    topic: "Snapshots",
    question: "Quelles colonnes de métadonnées un snapshot ajoute-t-il à la table cible ? (4 réponses)",
    choices: ["dbt_scd_id", "dbt_updated_at", "dbt_valid_from", "dbt_valid_to", "dbt_row_hash", "dbt_loaded_at"],
    answer: [0, 1, 2, 3],
    explanation: "Un snapshot (SCD type 2) ajoute `dbt_scd_id` (clé unique de la version), `dbt_updated_at`, `dbt_valid_from` et `dbt_valid_to` (`null` pour la version courante, sauf si `dbt_valid_to_current` est configuré). Avec `hard_deletes: new_record` (dbt 1.9+), une colonne `dbt_is_deleted` s'ajoute.",
    source: "https://docs.getdbt.com/docs/build/snapshots",
  },
  {
    id: "models-012",
    module: "models",
    topic: "Snapshots",
    question: "Vous devez snapshoter une table sans colonne fiable de mise à jour (`updated_at`). Quelle stratégie choisir ?",
    choices: [
      "`strategy: timestamp` avec `updated_at: current_timestamp()`",
      "`strategy: check` avec `check_cols` listant les colonnes à comparer (ou `all`)",
      "`strategy: merge` avec `unique_key`",
      "Il est impossible de snapshoter sans colonne d'horodatage",
    ],
    answer: [1],
    explanation: "La stratégie `check` compare les valeurs des colonnes listées dans `check_cols` (ou `all`) entre la source et la dernière version snapshotée. Elle est plus coûteuse que `timestamp` mais fonctionne sans colonne de mise à jour fiable.",
    source: "https://docs.getdbt.com/docs/build/snapshots#check-strategy",
  },
  {
    id: "models-013",
    module: "models",
    topic: "Seeds",
    question: "Quel est le cas d'usage approprié pour un seed ?",
    choices: [
      "Charger quotidiennement les exports CSV de l'ERP",
      "Stocker de petites tables de référence statiques versionnées avec le code (ex : liste de pays, mapping de codes)",
      "Charger des données volumineuses sans passer par un outil d'ingestion",
      "Sauvegarder les résultats de tests",
    ],
    answer: [1],
    explanation: "Les seeds sont des CSV versionnés dans le repo, chargés par `dbt seed`. Ils conviennent aux petites données de référence qui changent rarement. Ils ne sont pas faits pour de la donnée brute volumineuse ou fréquemment mise à jour, ni pour des données sensibles.",
    source: "https://docs.getdbt.com/docs/build/seeds",
  },
  {
    id: "models-014",
    module: "models",
    topic: "Modèles Python",
    question: "Quelle signature doit avoir la fonction principale d'un modèle Python dbt ?",
    choices: [
      "`def run(dbt, session)` qui renvoie une chaîne SQL",
      "`def model(dbt, session)` qui renvoie un DataFrame",
      "`def main()` qui écrit dans `dbt.target`",
      "`def model(context)` qui renvoie un dictionnaire",
    ],
    answer: [1],
    explanation: "Un modèle Python définit `def model(dbt, session)` et renvoie un DataFrame (Snowpark, PySpark ou pandas selon la plateforme). On accède aux dépendances via `dbt.ref('…')` / `dbt.source('…','…')` et à la config via `dbt.config(...)`. Le résultat est matérialisé en `table` ou `incremental` seulement.",
    source: "https://docs.getdbt.com/docs/build/python-models",
  },
  {
    id: "models-015",
    module: "models",
    topic: "Schémas personnalisés",
    question: "Le schéma cible du profil est `dbt_serge`. Un modèle est configuré avec `schema: marts`. Avec la macro `generate_schema_name` par défaut, dans quel schéma est-il créé ?",
    choices: ["marts", "dbt_serge", "dbt_serge_marts", "marts_dbt_serge"],
    answer: [2],
    explanation: "Le comportement par défaut concatène le schéma cible et le schéma personnalisé : `<target_schema>_<custom_schema>` → `dbt_serge_marts`. Cela évite que plusieurs développeurs écrasent le même schéma `marts`. Pour utiliser `marts` tel quel en prod, il faut surcharger la macro `generate_schema_name`.",
    source: "https://docs.getdbt.com/docs/build/custom-schemas",
  },
  {
    id: "models-016",
    module: "models",
    topic: "Hooks",
    question: "Vous voulez exécuter un `grant select` sur chaque modèle juste après sa création. Quelle approche est recommandée ?",
    choices: [
      "Un `on-run-end` hook qui boucle sur tous les modèles",
      "La config `grants` du modèle (ou du projet), qui gère les grants nativement",
      "Une macro appelée avec `dbt run-operation` après chaque run",
      "Un `pre-hook` sur le modèle",
    ],
    answer: [1],
    explanation: "Depuis dbt 1.2, la config `grants:` (`grants: {select: ['role_bi']}`) gère les permissions de manière native et idempotente, juste après la matérialisation. C'est préférable aux `post-hook` manuels. Le `pre-hook` s'exécute avant la création, donc trop tôt.",
    source: "https://docs.getdbt.com/reference/resource-configs/grants",
  },
  {
    id: "models-017",
    module: "models",
    topic: "Structure du projet",
    question: "Selon les bonnes pratiques dbt, quelle couche de modèles doit faire du renommage/typage de colonnes 1:1 avec la source, sans jointure ?",
    choices: ["marts", "intermediate", "staging", "sources"],
    answer: [2],
    explanation: "La couche **staging** (`stg_`) est un miroir nettoyé des sources : une source = un modèle staging, renommage, cast, pas de jointure ni d'agrégation. `intermediate` combine et transforme, `marts` expose les entités métier finales.",
    source: "https://docs.getdbt.com/best-practices/how-we-structure/1-guide-overview",
  },
]);
