// Module: Implementing dbt tests
QuizBank.add([
  {
    id: "tests-001",
    module: "tests",
    topic: "Generic tests",
    topic_fr: "Tests génériques",
    question: "What are the four generic tests shipped natively with dbt-core? (choose 4)",
    choices: ["unique", "not_null", "accepted_values", "relationships", "expect_column_values_to_be_between", "positive_values"],
    answer: [0, 1, 2, 3],
    explanation: "dbt-core ships `unique`, `not_null`, `accepted_values` and `relationships`. The others come from packages (`dbt_utils`, `dbt_expectations`) or from custom generic tests.",
    source: "https://docs.getdbt.com/docs/build/data-tests#generic-data-tests",
    fr: {
      question: "Quels sont les quatre tests génériques fournis nativement par dbt-core ? (4 réponses)",
      choices: ["unique", "not_null", "accepted_values", "relationships", "expect_column_values_to_be_between", "positive_values"],
      explanation: "dbt-core fournit `unique`, `not_null`, `accepted_values` et `relationships`. Les autres viennent de packages (`dbt_utils`, `dbt_expectations`) ou de tests génériques personnalisés.",
    },
  },
  {
    id: "tests-002",
    module: "tests",
    topic: "Singular tests",
    topic_fr: "Tests singuliers",
    question: "How does dbt decide that a **singular** test (SQL file in `tests/`) passes?",
    choices: [
      "The query returns `true`",
      "The query returns **zero rows**: every returned row is a failure",
      "The query returns at least one row",
      "The query runs without a SQL error",
    ],
    answer: [1],
    explanation: "A dbt test is a query that selects the **failing** rows. 0 rows = pass, N rows = N failures. This holds for singular and generic tests alike. Hence the pattern: `select * from {{ ref('x') }} where amount < 0`.",
    source: "https://docs.getdbt.com/docs/build/data-tests#singular-data-tests",
    fr: {
      question: "Comment dbt décide-t-il qu'un test **singulier** (fichier SQL dans `tests/`) passe ?",
      choices: [
        "La requête renvoie `true`",
        "La requête renvoie **zéro ligne** : chaque ligne renvoyée est un échec",
        "La requête renvoie au moins une ligne",
        "La requête s'exécute sans erreur SQL",
      ],
      explanation: "Un test dbt est une requête qui sélectionne les lignes **en anomalie**. 0 ligne = pass, N lignes = N failures. C'est vrai pour les tests singuliers comme génériques. D'où le pattern : `select * from {{ ref('x') }} where montant < 0`.",
    },
  },
  {
    id: "tests-003",
    module: "tests",
    topic: "Severity",
    topic_fr: "Sévérité",
    question: "A test is configured with `severity: error`, `error_if: \">10\"`, `warn_if: \">0\"`. It returns 5 rows. What is its status?",
    choices: ["pass", "warn", "error", "fail"],
    answer: [1],
    explanation: "With `severity: error`, dbt first evaluates `error_if`: 5 > 10 is false, so no error. It then evaluates `warn_if`: 5 > 0 is true → **warn**. A warn does not block downstream nodes in `dbt build`. Defaults: `error_if: \"!=0\"`, `warn_if: \"!=0\"`.",
    source: "https://docs.getdbt.com/reference/resource-configs/severity",
    fr: {
      question: "Un test est configuré avec `severity: error`, `error_if: \">10\"`, `warn_if: \">0\"`. Il renvoie 5 lignes. Quel est son statut ?",
      choices: ["pass", "warn", "error", "fail"],
      explanation: "Avec `severity: error`, dbt évalue d'abord `error_if` : 5 > 10 est faux, donc pas d'erreur. Il évalue ensuite `warn_if` : 5 > 0 est vrai → **warn**. Un warn ne bloque pas les nœuds aval dans `dbt build`. Valeurs par défaut : `error_if: \"!=0\"`, `warn_if: \"!=0\"`.",
    },
  },
  {
    id: "tests-004",
    module: "tests",
    topic: "Test configuration",
    topic_fr: "Configuration des tests",
    question: "What does the `store_failures: true` config do on a test?",
    choices: [
      "Prevents the test from failing",
      "Writes the failing rows to a table in the warehouse (by default in the `<schema>_dbt_test__audit` schema)",
      "Saves the results to `run_results.json`",
      "Sends an e-mail alert",
    ],
    answer: [1],
    explanation: "`store_failures` materializes the failing rows in a table (one per test), which makes investigation easier without re-running the query. The target schema is configurable via `schema:` on the test. `store_failures_as` (1.7+) lets you choose `table`, `view` or `ephemeral`.",
    source: "https://docs.getdbt.com/reference/resource-configs/store_failures",
    fr: {
      question: "Que fait la config `store_failures: true` sur un test ?",
      choices: [
        "Empêche le test d'échouer",
        "Écrit les lignes en échec dans une table de l'entrepôt (par défaut dans le schéma `<schema>_dbt_test__audit`)",
        "Sauvegarde les résultats dans `run_results.json`",
        "Envoie une alerte par e-mail",
      ],
      explanation: "`store_failures` matérialise les lignes en anomalie dans une table (une par test), ce qui facilite l'investigation sans relancer la requête. Le schéma cible est configurable via `schema:` sur le test. `store_failures_as` (1.7+) permet de choisir `table`, `view` ou `ephemeral`.",
    },
  },
  {
    id: "tests-005",
    module: "tests",
    topic: "Unit tests",
    topic_fr: "Unit tests",
    question: "Which statements are true about dbt **unit tests** (1.8+)? (choose 2)",
    choices: [
      "They are defined in YAML under the `unit_tests:` key with `given` (mocked data) and `expect` entries",
      "They are only supported for SQL models",
      "They replace data tests (`unique`, `not_null`…)",
      "They run after the model is materialized in `dbt build`",
    ],
    answer: [0, 1],
    explanation: "Unit tests check a model's **logic** on mocked inputs (`given`) against an expected output (`expect`). Only for SQL models (not Python). In `dbt build`, they run **before** the model is materialized: if the unit test fails, the model is not built. They complement data tests, they do not replace them.",
    source: "https://docs.getdbt.com/docs/build/unit-tests",
    fr: {
      question: "Quelles affirmations sont vraies sur les **unit tests** dbt (1.8+) ? (2 réponses)",
      choices: [
        "Ils se définissent en YAML sous la clé `unit_tests:` avec des entrées `given` (données mockées) et `expect`",
        "Ils ne sont supportés que pour les modèles SQL",
        "Ils remplacent les tests de données (`unique`, `not_null`…)",
        "Ils sont exécutés après la matérialisation du modèle dans `dbt build`",
      ],
      explanation: "Les unit tests vérifient la **logique** d'un modèle sur des entrées mockées (`given`) contre une sortie attendue (`expect`). Uniquement pour les modèles SQL (pas Python). Dans `dbt build`, ils s'exécutent **avant** la matérialisation du modèle : si le unit test échoue, le modèle n'est pas construit. Ils complètent les data tests, ils ne les remplacent pas.",
    },
  },
  {
    id: "tests-006",
    module: "tests",
    topic: "Unit tests",
    topic_fr: "Unit tests",
    question: "You run `dbt test --select test_type:unit` in an empty dev schema and get an error because the parent models do not exist. What is the recommended solution?",
    choices: [
      "Add `--no-introspection`",
      "Build the parents first, e.g. `dbt run --select +my_model --empty`",
      "Declare the parents as `ephemeral`",
      "Unit tests cannot run in dev",
    ],
    answer: [1],
    explanation: "dbt needs the parents in the warehouse to know their schema (column types) and build the mocked CTEs. `--empty` creates those objects empty at minimal cost. Using `format: sql` with explicit fixtures does not remove that requirement.",
    source: "https://docs.getdbt.com/docs/build/unit-tests#before-you-begin",
    fr: {
      question: "Vous lancez `dbt test --select test_type:unit` dans un schéma de dev vide et obtenez une erreur car les modèles parents n'existent pas. Quelle est la solution recommandée ?",
      choices: [
        "Ajouter `--no-introspection`",
        "Construire d'abord les parents, par ex. `dbt run --select +mon_modele --empty`",
        "Déclarer les parents en `ephemeral`",
        "Les unit tests ne peuvent pas tourner en dev",
      ],
      explanation: "dbt a besoin des parents dans l'entrepôt pour connaître leur schéma (types de colonnes) et construire les CTE mockées. `--empty` crée ces objets vides à moindre coût. Le `format: sql` avec des fixtures explicites ne dispense pas de cette étape.",
    },
  },
  {
    id: "tests-007",
    module: "tests",
    topic: "Custom generic tests",
    topic_fr: "Tests génériques personnalisés",
    question: "How do you declare a custom generic test `is_positive` reusable on any column?",
    choices: [
      "A `tests/is_positive.sql` file containing a `select`",
      "A `{% test is_positive(model, column_name) %} … {% endtest %}` block in `tests/generic/` or `macros/`",
      "A `{% macro test_is_positive() %}` macro in `dbt_project.yml`",
      "A `custom_tests:` entry in `schema.yml`",
    ],
    answer: [1],
    explanation: "A generic test is a `{% test name(model, column_name, …) %}` block placed in `tests/generic/` (or `macros/`). It is then used in YAML like a native test: `data_tests: - is_positive`. Extra arguments can be passed in YAML. A SQL file in `tests/` without a `test` block is a singular test, not reusable.",
    source: "https://docs.getdbt.com/best-practices/writing-custom-generic-tests",
    fr: {
      question: "Comment déclarer un test générique personnalisé `is_positive` réutilisable sur n'importe quelle colonne ?",
      choices: [
        "Un fichier `tests/is_positive.sql` contenant un `select`",
        "Un bloc `{% test is_positive(model, column_name) %} … {% endtest %}` dans `tests/generic/` ou `macros/`",
        "Une macro `{% macro test_is_positive() %}` dans `dbt_project.yml`",
        "Une entrée `custom_tests:` dans `schema.yml`",
      ],
      explanation: "Un test générique est un bloc `{% test nom(model, column_name, …) %}` placé dans `tests/generic/` (ou `macros/`). Il s'utilise ensuite dans le YAML comme un test natif : `data_tests: - is_positive`. Des arguments supplémentaires peuvent être passés en YAML. Un fichier SQL dans `tests/` sans bloc `test` est un test singulier, non réutilisable.",
    },
  },
  {
    id: "tests-008",
    module: "tests",
    topic: "Test configuration",
    topic_fr: "Configuration des tests",
    question: "You want a `not_null` test to apply only to rows from the last 30 days. Which config do you use?",
    choices: [
      "`limit: 30`",
      "`where: \"created_at >= dateadd(day, -30, current_date)\"`",
      "`filter: last_30_days`",
      "Impossible with a native generic test",
    ],
    answer: [1],
    explanation: "The `where` config adds a filter clause to the test query. It applies to any generic test. `limit` limits the number of returned rows (useful with `store_failures`), not the tested scope.",
    source: "https://docs.getdbt.com/reference/resource-configs/where",
    fr: {
      question: "Vous voulez qu'un test `not_null` ne s'applique qu'aux lignes des 30 derniers jours. Quelle config utiliser ?",
      choices: [
        "`limit: 30`",
        "`where: \"created_at >= dateadd(day, -30, current_date)\"`",
        "`filter: last_30_days`",
        "Impossible avec un test générique natif",
      ],
      explanation: "La config `where` ajoute une clause de filtre à la requête du test. Elle s'applique à tout test générique. `limit` limite le nombre de lignes renvoyées (utile avec `store_failures`), pas le périmètre testé.",
    },
  },
  {
    id: "tests-009",
    module: "tests",
    topic: "Tests on sources",
    topic_fr: "Tests sur sources",
    question: "Can you define `unique` / `not_null` tests directly on a **source**?",
    choices: [
      "No, tests only apply to models",
      "Yes, in `sources.yml` under the table's columns, and you run them with `dbt test --select source:source_name`",
      "Yes, but only singular tests",
      "Yes, but only through `dbt source freshness`",
    ],
    answer: [1],
    explanation: "Sources accept the same tests as models. Testing sources lets you detect a raw data problem **before** building anything (`dbt test --select source:*` at the start of a job). Freshness is a separate mechanism.",
    source: "https://docs.getdbt.com/docs/build/sources#testing-and-documenting-sources",
    fr: {
      question: "Peut-on définir des tests `unique` / `not_null` directement sur une **source** ?",
      choices: [
        "Non, les tests ne s'appliquent qu'aux modèles",
        "Oui, dans `sources.yml` sous les colonnes de la table, et on les lance avec `dbt test --select source:nom_source`",
        "Oui, mais uniquement des tests singuliers",
        "Oui, mais uniquement via `dbt source freshness`",
      ],
      explanation: "Les sources acceptent les mêmes tests que les modèles. Tester les sources permet de détecter un problème de données brutes **avant** de construire quoi que ce soit (`dbt test --select source:*` en début de job). La fraîcheur (`freshness`) est un mécanisme distinct.",
    },
  },
  {
    id: "tests-010",
    module: "tests",
    topic: "Generic tests",
    topic_fr: "Tests génériques",
    question: "How should the `relationships` test be configured to check that every `customer_id` in `fct_orders` exists in `dim_customers`?",
    choices: [
      "On `dim_customers.customer_id`: `relationships: {to: ref('fct_orders'), field: customer_id}`",
      "On `fct_orders.customer_id`: `relationships: {to: ref('dim_customers'), field: customer_id}`",
      "On both models simultaneously",
      "On `fct_orders` with `foreign_key: dim_customers`",
    ],
    answer: [1],
    explanation: "The test goes on the **child** column (foreign key) and points to the **parent** model via `to` and its column via `field`. It checks referential integrity: every child value must exist in the parent (child `null`s are ignored).",
    source: "https://docs.getdbt.com/reference/resource-properties/data-tests#relationships",
    fr: {
      question: "Comment le test `relationships` doit-il être configuré pour vérifier que chaque `customer_id` de `fct_orders` existe dans `dim_customers` ?",
      choices: [
        "Sur `dim_customers.customer_id` : `relationships: {to: ref('fct_orders'), field: customer_id}`",
        "Sur `fct_orders.customer_id` : `relationships: {to: ref('dim_customers'), field: customer_id}`",
        "Sur les deux modèles simultanément",
        "Sur `fct_orders` avec `foreign_key: dim_customers`",
      ],
      explanation: "Le test se pose sur la colonne **enfant** (clé étrangère) et pointe vers le modèle **parent** via `to` et sa colonne via `field`. Il vérifie l'intégrité référentielle : toute valeur de l'enfant doit exister dans le parent (les `null` de l'enfant sont ignorés).",
    },
  },
  {
    id: "tests-011",
    module: "tests",
    topic: "Test selection",
    topic_fr: "Sélection de tests",
    question: "You run `dbt test --select stg_orders`. Is a `relationships` test defined on `fct_orders` and pointing to `stg_orders` executed?",
    choices: [
      "Yes, by default (`--indirect-selection eager`): any test with **at least one** selected parent is included",
      "No, only the tests defined in `stg_orders`' YAML run",
      "Yes, but only with `--indirect-selection cautious`",
      "No, `relationships` tests are never selected indirectly",
    ],
    answer: [0],
    explanation: "The default `eager` mode includes any test touching a selected node, even if its other parents are not selected. `cautious` only includes tests whose parents are **all** selected; `buildable` = cautious + parents in the expanded selection; `empty` = no indirect tests.",
    source: "https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection",
    fr: {
      question: "Vous lancez `dbt test --select stg_orders`. Un test `relationships` défini sur `fct_orders` et pointant vers `stg_orders` est-il exécuté ?",
      choices: [
        "Oui, par défaut (`--indirect-selection eager`) : tout test dont **au moins un** parent est sélectionné est inclus",
        "Non, seuls les tests définis dans le YAML de `stg_orders` sont exécutés",
        "Oui, mais seulement avec `--indirect-selection cautious`",
        "Non, les tests `relationships` ne sont jamais sélectionnés indirectement",
      ],
      explanation: "Le mode par défaut `eager` inclut tout test qui touche un nœud sélectionné, même si ses autres parents ne le sont pas. `cautious` n'inclut que les tests dont **tous** les parents sont sélectionnés ; `buildable` = cautious + parents dans la sélection élargie ; `empty` = aucun test indirect.",
    },
  },
]);
