// Module : Implémenter des tests dbt
QuizBank.add([
  {
    id: "tests-001",
    module: "tests",
    topic: "Tests génériques",
    question: "Quels sont les quatre tests génériques fournis nativement par dbt-core ? (4 réponses)",
    choices: ["unique", "not_null", "accepted_values", "relationships", "expect_column_values_to_be_between", "positive_values"],
    answer: [0, 1, 2, 3],
    explanation: "dbt-core fournit `unique`, `not_null`, `accepted_values` et `relationships`. Les autres viennent de packages (`dbt_utils`, `dbt_expectations`) ou de tests génériques personnalisés.",
    source: "https://docs.getdbt.com/docs/build/data-tests#generic-data-tests",
  },
  {
    id: "tests-002",
    module: "tests",
    topic: "Tests singuliers",
    question: "Comment dbt décide-t-il qu'un test **singulier** (fichier SQL dans `tests/`) passe ?",
    choices: [
      "La requête renvoie `true`",
      "La requête renvoie **zéro ligne** : chaque ligne renvoyée est un échec",
      "La requête renvoie au moins une ligne",
      "La requête s'exécute sans erreur SQL",
    ],
    answer: [1],
    explanation: "Un test dbt est une requête qui sélectionne les lignes **en anomalie**. 0 ligne = pass, N lignes = N failures. C'est vrai pour les tests singuliers comme génériques. D'où le pattern : `select * from {{ ref('x') }} where montant < 0`.",
    source: "https://docs.getdbt.com/docs/build/data-tests#singular-data-tests",
  },
  {
    id: "tests-003",
    module: "tests",
    topic: "Sévérité",
    question: "Un test est configuré avec `severity: error`, `error_if: \">10\"`, `warn_if: \">0\"`. Il renvoie 5 lignes. Quel est son statut ?",
    choices: ["pass", "warn", "error", "fail"],
    answer: [1],
    explanation: "Avec `severity: error`, dbt évalue d'abord `error_if` : 5 > 10 est faux, donc pas d'erreur. Il évalue ensuite `warn_if` : 5 > 0 est vrai → **warn**. Un warn ne bloque pas les nœuds aval dans `dbt build`. Valeurs par défaut : `error_if: \"!=0\"`, `warn_if: \"!=0\"`.",
    source: "https://docs.getdbt.com/reference/resource-configs/severity",
  },
  {
    id: "tests-004",
    module: "tests",
    topic: "Configuration des tests",
    question: "Que fait la config `store_failures: true` sur un test ?",
    choices: [
      "Empêche le test d'échouer",
      "Écrit les lignes en échec dans une table de l'entrepôt (par défaut dans le schéma `<schema>_dbt_test__audit`)",
      "Sauvegarde les résultats dans `run_results.json`",
      "Envoie une alerte par e-mail",
    ],
    answer: [1],
    explanation: "`store_failures` matérialise les lignes en anomalie dans une table (une par test), ce qui facilite l'investigation sans relancer la requête. Le schéma cible est configurable via `schema:` sur le test. `store_failures_as` (1.7+) permet de choisir `table`, `view` ou `ephemeral`.",
    source: "https://docs.getdbt.com/reference/resource-configs/store_failures",
  },
  {
    id: "tests-005",
    module: "tests",
    topic: "Unit tests",
    question: "Quelles affirmations sont vraies sur les **unit tests** dbt (1.8+) ? (2 réponses)",
    choices: [
      "Ils se définissent en YAML sous la clé `unit_tests:` avec des entrées `given` (données mockées) et `expect`",
      "Ils ne sont supportés que pour les modèles SQL",
      "Ils remplacent les tests de données (`unique`, `not_null`…)",
      "Ils sont exécutés après la matérialisation du modèle dans `dbt build`",
    ],
    answer: [0, 1],
    explanation: "Les unit tests vérifient la **logique** d'un modèle sur des entrées mockées (`given`) contre une sortie attendue (`expect`). Uniquement pour les modèles SQL (pas Python, pas de matérialisation `ephemeral` seuls). Dans `dbt build`, ils s'exécutent **avant** la matérialisation du modèle : si le unit test échoue, le modèle n'est pas construit. Ils complètent les data tests, ils ne les remplacent pas.",
    source: "https://docs.getdbt.com/docs/build/unit-tests",
  },
  {
    id: "tests-006",
    module: "tests",
    topic: "Unit tests",
    question: "Vous lancez `dbt test --select test_type:unit` dans un schéma de dev vide et obtenez une erreur car les modèles parents n'existent pas. Quelle est la solution recommandée ?",
    choices: [
      "Ajouter `--no-introspection`",
      "Construire d'abord les parents, par ex. `dbt run --select +mon_modele --empty`",
      "Déclarer les parents en `ephemeral`",
      "Les unit tests ne peuvent pas tourner en dev",
    ],
    answer: [1],
    explanation: "dbt a besoin des parents dans l'entrepôt pour connaître leur schéma (types de colonnes) et construire les CTE mockées. `--empty` crée ces objets vides à moindre coût. Alternative : le `format: sql` avec des fixtures explicites ne dispense pas de cette étape.",
    source: "https://docs.getdbt.com/docs/build/unit-tests#before-you-begin",
  },
  {
    id: "tests-007",
    module: "tests",
    topic: "Tests génériques personnalisés",
    question: "Comment déclarer un test générique personnalisé `is_positive` réutilisable sur n'importe quelle colonne ?",
    choices: [
      "Un fichier `tests/is_positive.sql` contenant un `select`",
      "Un bloc `{% test is_positive(model, column_name) %} … {% endtest %}` dans `tests/generic/` ou `macros/`",
      "Une macro `{% macro test_is_positive() %}` dans `dbt_project.yml`",
      "Une entrée `custom_tests:` dans `schema.yml`",
    ],
    answer: [1],
    explanation: "Un test générique est un bloc `{% test nom(model, column_name, …) %}` placé dans `tests/generic/` (ou `macros/`). Il s'utilise ensuite dans le YAML comme un test natif : `data_tests: - is_positive`. Des arguments supplémentaires peuvent être passés en YAML. Un fichier SQL dans `tests/` sans bloc `test` est un test singulier, non réutilisable.",
    source: "https://docs.getdbt.com/best-practices/writing-custom-generic-tests",
  },
  {
    id: "tests-008",
    module: "tests",
    topic: "Configuration des tests",
    question: "Vous voulez qu'un test `not_null` ne s'applique qu'aux lignes des 30 derniers jours. Quelle config utiliser ?",
    choices: [
      "`limit: 30`",
      "`where: \"created_at >= dateadd(day, -30, current_date)\"`",
      "`filter: last_30_days`",
      "Impossible avec un test générique natif",
    ],
    answer: [1],
    explanation: "La config `where` ajoute une clause de filtre à la requête du test. Elle s'applique à tout test générique. `limit` limite le nombre de lignes renvoyées (utile avec `store_failures`), pas le périmètre testé.",
    source: "https://docs.getdbt.com/reference/resource-configs/where",
  },
  {
    id: "tests-009",
    module: "tests",
    topic: "Tests sur sources",
    question: "Peut-on définir des tests `unique` / `not_null` directement sur une **source** ?",
    choices: [
      "Non, les tests ne s'appliquent qu'aux modèles",
      "Oui, dans `sources.yml` sous les colonnes de la table, et on les lance avec `dbt test --select source:nom_source`",
      "Oui, mais uniquement des tests singuliers",
      "Oui, mais uniquement via `dbt source freshness`",
    ],
    answer: [1],
    explanation: "Les sources acceptent les mêmes tests que les modèles. Tester les sources permet de détecter un problème de données brutes **avant** de construire quoi que ce soit (`dbt test --select source:*` en début de job). La fraîcheur (`freshness`) est un mécanisme distinct.",
    source: "https://docs.getdbt.com/docs/build/sources#testing-and-documenting-sources",
  },
  {
    id: "tests-010",
    module: "tests",
    topic: "Tests génériques",
    question: "Comment le test `relationships` doit-il être configuré pour vérifier que chaque `customer_id` de `fct_orders` existe dans `dim_customers` ?",
    choices: [
      "Sur `dim_customers.customer_id` : `relationships: {to: ref('fct_orders'), field: customer_id}`",
      "Sur `fct_orders.customer_id` : `relationships: {to: ref('dim_customers'), field: customer_id}`",
      "Sur les deux modèles simultanément",
      "Sur `fct_orders` avec `foreign_key: dim_customers`",
    ],
    answer: [1],
    explanation: "Le test se pose sur la colonne **enfant** (clé étrangère) et pointe vers le modèle **parent** via `to` et sa colonne via `field`. Il vérifie l'intégrité référentielle : toute valeur de l'enfant doit exister dans le parent (les `null` de l'enfant sont ignorés).",
    source: "https://docs.getdbt.com/reference/resource-properties/data-tests#relationships",
  },
  {
    id: "tests-011",
    module: "tests",
    topic: "Sélection de tests",
    question: "Vous lancez `dbt test --select stg_orders`. Un test `relationships` défini sur `fct_orders` et pointant vers `stg_orders` est-il exécuté ?",
    choices: [
      "Oui, par défaut (`--indirect-selection eager`) : tout test dont **au moins un** parent est sélectionné est inclus",
      "Non, seuls les tests définis dans le YAML de `stg_orders` sont exécutés",
      "Oui, mais seulement avec `--indirect-selection cautious`",
      "Non, les tests `relationships` ne sont jamais sélectionnés indirectement",
    ],
    answer: [0],
    explanation: "Le mode par défaut `eager` inclut tout test qui touche un nœud sélectionné, même si ses autres parents ne le sont pas. `cautious` n'inclut que les tests dont **tous** les parents sont sélectionnés ; `buildable` = cautious + parents dans la sélection élargie ; `empty` = aucun test indirect.",
    source: "https://docs.getdbt.com/reference/node-selection/test-selection-examples#indirect-selection",
  },
]);
