// Module : Créer et maintenir la documentation
QuizBank.add([
  {
    id: "docs-001",
    module: "docs",
    topic: "Doc blocks",
    question: "Comment réutiliser une même description longue (Markdown) pour la colonne `customer_id` dans plusieurs modèles ?",
    choices: [
      "Copier la description dans chaque YAML",
      "Définir un `{% docs customer_id %} … {% enddocs %}` dans un fichier `.md` et l'appeler avec `description: \"{{ doc('customer_id') }}\"`",
      "Utiliser un anchor YAML `&customer_id`",
      "Mettre la description dans `dbt_project.yml` sous `descriptions:`",
    ],
    answer: [1],
    explanation: "Les **doc blocks** se définissent dans n'importe quel fichier `.md` des `docs-paths`/`model-paths` avec `{% docs nom %}`. On les référence via `{{ doc('nom') }}` dans n'importe quelle `description`. Le Markdown y est supporté (tableaux, listes…).",
    source: "https://docs.getdbt.com/docs/build/documentation#using-docs-blocks",
  },
  {
    id: "docs-002",
    module: "docs",
    topic: "dbt docs",
    question: "Quels fichiers `dbt docs generate` produit-il dans `target/` pour alimenter le site de documentation ? (2 réponses)",
    choices: ["manifest.json", "catalog.json", "run_results.json", "sources.json"],
    answer: [0, 1],
    explanation: "`dbt docs generate` compile le projet (→ `manifest.json` : nœuds, descriptions, DAG) et interroge l'entrepôt (→ `catalog.json` : colonnes, types, stats des objets existants). `dbt docs serve` sert ensuite le site à partir de ces fichiers et de `index.html`.",
    source: "https://docs.getdbt.com/reference/commands/cmd-docs",
  },
  {
    id: "docs-003",
    module: "docs",
    topic: "dbt docs",
    question: "Dans le site de documentation, les types de colonnes et le nombre de lignes d'une table proviennent de quel artefact ?",
    choices: ["manifest.json", "catalog.json", "schema.yml", "run_results.json"],
    answer: [1],
    explanation: "`catalog.json` est rempli en interrogeant l'`information_schema` de l'entrepôt : c'est là que viennent les types réels, les stats (lignes, octets). `manifest.json` ne connaît que ce qui est déclaré dans le code et le YAML. Si un modèle n'a jamais été matérialisé, il n'apparaît pas dans le catalog.",
    source: "https://docs.getdbt.com/reference/artifacts/catalog-json",
  },
  {
    id: "docs-004",
    module: "docs",
    topic: "persist_docs",
    question: "À quoi sert la config `persist_docs: {relation: true, columns: true}` ?",
    choices: [
      "À inclure les descriptions dans le site `dbt docs`",
      "À écrire les descriptions du YAML comme **commentaires** sur les tables/vues et colonnes dans l'entrepôt",
      "À exporter la documentation en PDF",
      "À sauvegarder `catalog.json` entre les runs",
    ],
    answer: [1],
    explanation: "`persist_docs` pousse les `description` vers l'entrepôt (`comment on table…`, `comment on column…`) au moment de la matérialisation. Les descriptions deviennent visibles dans les outils de catalogue de la plateforme (ex : Snowsight). Les descriptions apparaissent dans `dbt docs` de toute façon, sans cette config.",
    source: "https://docs.getdbt.com/reference/resource-configs/persist_docs",
  },
  {
    id: "docs-005",
    module: "docs",
    topic: "Doc blocks",
    question: "Comment personnaliser la page d'accueil du site `dbt docs` ?",
    choices: [
      "Modifier `target/index.html`",
      "Définir un doc block nommé `__overview__` dans un fichier `.md`",
      "Ajouter `homepage: README.md` dans `dbt_project.yml`",
      "Impossible, la page d'accueil est fixe",
    ],
    answer: [1],
    explanation: "Un doc block `{% docs __overview__ %}` remplace le contenu par défaut de la page d'accueil. Pour un package, `{% docs __<package_name>__ %}` fait de même pour la page du package. `target/index.html` est régénéré à chaque `docs generate`.",
    source: "https://docs.getdbt.com/docs/build/documentation#custom-project-level-overviews",
  },
  {
    id: "docs-006",
    module: "docs",
    topic: "Propriétés YAML",
    question: "Vous voulez attacher des métadonnées libres (ex : `owner`, `pii: true`, `sla`) à un modèle, consultables dans `manifest.json` et le site docs. Quelle propriété utiliser ?",
    choices: ["`tags`", "`meta`", "`vars`", "`labels`"],
    answer: [1],
    explanation: "`meta` accepte un dictionnaire arbitraire au niveau modèle, colonne, source, seed… Il est exposé dans le manifest et le site docs, et exploitable dans les macros via `config.get('meta')` ou `graph`. `tags` est une liste de chaînes servant surtout à la sélection.",
    source: "https://docs.getdbt.com/reference/resource-configs/meta",
  },
]);
