// Module: Creating and maintaining documentation
QuizBank.add([
  {
    id: "docs-001",
    module: "docs",
    topic: "Doc blocks",
    topic_fr: "Doc blocks",
    question: "How do you reuse the same long (Markdown) description for the `customer_id` column across several models?",
    choices: [
      "Copy the description into each YAML",
      "Define a `{% docs customer_id %} … {% enddocs %}` in a `.md` file and reference it with `description: \"{{ doc('customer_id') }}\"`",
      "Use a YAML anchor `&customer_id`",
      "Put the description in `dbt_project.yml` under `descriptions:`",
    ],
    answer: [1],
    explanation: "**Doc blocks** are defined in any `.md` file under `docs-paths`/`model-paths` with `{% docs name %}`. They are referenced with `{{ doc('name') }}` in any `description`. Markdown is supported (tables, lists…).",
    source: "https://docs.getdbt.com/docs/build/documentation#using-docs-blocks",
    fr: {
      question: "Comment réutiliser une même description longue (Markdown) pour la colonne `customer_id` dans plusieurs modèles ?",
      choices: [
        "Copier la description dans chaque YAML",
        "Définir un `{% docs customer_id %} … {% enddocs %}` dans un fichier `.md` et l'appeler avec `description: \"{{ doc('customer_id') }}\"`",
        "Utiliser un anchor YAML `&customer_id`",
        "Mettre la description dans `dbt_project.yml` sous `descriptions:`",
      ],
      explanation: "Les **doc blocks** se définissent dans n'importe quel fichier `.md` des `docs-paths`/`model-paths` avec `{% docs nom %}`. On les référence via `{{ doc('nom') }}` dans n'importe quelle `description`. Le Markdown y est supporté (tableaux, listes…).",
    },
  },
  {
    id: "docs-002",
    module: "docs",
    topic: "dbt docs",
    topic_fr: "dbt docs",
    question: "Which files does `dbt docs generate` produce in `target/` to feed the documentation site? (choose 2)",
    choices: ["manifest.json", "catalog.json", "run_results.json", "sources.json"],
    answer: [0, 1],
    explanation: "`dbt docs generate` compiles the project (→ `manifest.json`: nodes, descriptions, DAG) and queries the warehouse (→ `catalog.json`: columns, types, stats of existing objects). `dbt docs serve` then serves the site from those files and `index.html`.",
    source: "https://docs.getdbt.com/reference/commands/cmd-docs",
    fr: {
      question: "Quels fichiers `dbt docs generate` produit-il dans `target/` pour alimenter le site de documentation ? (2 réponses)",
      choices: ["manifest.json", "catalog.json", "run_results.json", "sources.json"],
      explanation: "`dbt docs generate` compile le projet (→ `manifest.json` : nœuds, descriptions, DAG) et interroge l'entrepôt (→ `catalog.json` : colonnes, types, stats des objets existants). `dbt docs serve` sert ensuite le site à partir de ces fichiers et de `index.html`.",
    },
  },
  {
    id: "docs-003",
    module: "docs",
    topic: "dbt docs",
    topic_fr: "dbt docs",
    question: "In the documentation site, where do a table's column types and row count come from?",
    choices: ["manifest.json", "catalog.json", "schema.yml", "run_results.json"],
    answer: [1],
    explanation: "`catalog.json` is filled by querying the warehouse's `information_schema`: that is where the real types and stats (rows, bytes) come from. `manifest.json` only knows what is declared in code and YAML. If a model was never materialized, it does not appear in the catalog.",
    source: "https://docs.getdbt.com/reference/artifacts/catalog-json",
    fr: {
      question: "Dans le site de documentation, les types de colonnes et le nombre de lignes d'une table proviennent de quel artefact ?",
      choices: ["manifest.json", "catalog.json", "schema.yml", "run_results.json"],
      explanation: "`catalog.json` est rempli en interrogeant l'`information_schema` de l'entrepôt : c'est là que viennent les types réels, les stats (lignes, octets). `manifest.json` ne connaît que ce qui est déclaré dans le code et le YAML. Si un modèle n'a jamais été matérialisé, il n'apparaît pas dans le catalog.",
    },
  },
  {
    id: "docs-004",
    module: "docs",
    topic: "persist_docs",
    topic_fr: "persist_docs",
    question: "What is the `persist_docs: {relation: true, columns: true}` config for?",
    choices: [
      "Including descriptions in the `dbt docs` site",
      "Writing the YAML descriptions as **comments** on tables/views and columns in the warehouse",
      "Exporting the documentation as PDF",
      "Keeping `catalog.json` between runs",
    ],
    answer: [1],
    explanation: "`persist_docs` pushes `description`s to the warehouse (`comment on table…`, `comment on column…`) at materialization time. Descriptions become visible in the platform's catalog tools (e.g. Snowsight). Descriptions appear in `dbt docs` anyway, without this config.",
    source: "https://docs.getdbt.com/reference/resource-configs/persist_docs",
    fr: {
      question: "À quoi sert la config `persist_docs: {relation: true, columns: true}` ?",
      choices: [
        "À inclure les descriptions dans le site `dbt docs`",
        "À écrire les descriptions du YAML comme **commentaires** sur les tables/vues et colonnes dans l'entrepôt",
        "À exporter la documentation en PDF",
        "À sauvegarder `catalog.json` entre les runs",
      ],
      explanation: "`persist_docs` pousse les `description` vers l'entrepôt (`comment on table…`, `comment on column…`) au moment de la matérialisation. Les descriptions deviennent visibles dans les outils de catalogue de la plateforme (ex : Snowsight). Les descriptions apparaissent dans `dbt docs` de toute façon, sans cette config.",
    },
  },
  {
    id: "docs-005",
    module: "docs",
    topic: "Doc blocks",
    topic_fr: "Doc blocks",
    question: "How do you customize the home page of the `dbt docs` site?",
    choices: [
      "Edit `target/index.html`",
      "Define a doc block named `__overview__` in a `.md` file",
      "Add `homepage: README.md` in `dbt_project.yml`",
      "Impossible, the home page is fixed",
    ],
    answer: [1],
    explanation: "A `{% docs __overview__ %}` doc block replaces the default home page content. For a package, `{% docs __<package_name>__ %}` does the same for the package page. `target/index.html` is regenerated on every `docs generate`.",
    source: "https://docs.getdbt.com/docs/build/documentation#custom-project-level-overviews",
    fr: {
      question: "Comment personnaliser la page d'accueil du site `dbt docs` ?",
      choices: [
        "Modifier `target/index.html`",
        "Définir un doc block nommé `__overview__` dans un fichier `.md`",
        "Ajouter `homepage: README.md` dans `dbt_project.yml`",
        "Impossible, la page d'accueil est fixe",
      ],
      explanation: "Un doc block `{% docs __overview__ %}` remplace le contenu par défaut de la page d'accueil. Pour un package, `{% docs __<package_name>__ %}` fait de même pour la page du package. `target/index.html` est régénéré à chaque `docs generate`.",
    },
  },
  {
    id: "docs-006",
    module: "docs",
    topic: "YAML properties",
    topic_fr: "Propriétés YAML",
    question: "You want to attach free-form metadata (e.g. `owner`, `pii: true`, `sla`) to a model, visible in `manifest.json` and the docs site. Which property do you use?",
    choices: ["`tags`", "`meta`", "`vars`", "`labels`"],
    answer: [1],
    explanation: "`meta` accepts an arbitrary dictionary at model, column, source, seed level… It is exposed in the manifest and the docs site, and usable in macros through `config.get('meta')` or `graph`. `tags` is a list of strings mostly used for selection.",
    source: "https://docs.getdbt.com/reference/resource-configs/meta",
    fr: {
      question: "Vous voulez attacher des métadonnées libres (ex : `owner`, `pii: true`, `sla`) à un modèle, consultables dans `manifest.json` et le site docs. Quelle propriété utiliser ?",
      choices: ["`tags`", "`meta`", "`vars`", "`labels`"],
      explanation: "`meta` accepte un dictionnaire arbitraire au niveau modèle, colonne, source, seed… Il est exposé dans le manifest et le site docs, et exploitable dans les macros via `config.get('meta')` ou `graph`. `tags` est une liste de chaînes servant surtout à la sélection.",
    },
  },
]);
