// Module: Leveraging dbt state (state:modified, defer, clone, result:)
QuizBank.add([
  {
    id: "state-001",
    module: "state",
    topic: "state:modified",
    topic_fr: "state:modified",
    question: "What must you provide to dbt for `--select state:modified` to work?",
    choices: [
      "A git repository with an uncommitted diff",
      "An artifacts folder (containing the `manifest.json` of a reference run) via `--state <path>` or `DBT_STATE`",
      "The `run_results.json` of the last local run",
      "Nothing, dbt compares with `target/` automatically",
    ],
    answer: [1],
    explanation: "`state:modified` compares the current manifest with a **reference manifest** (typically production's, downloaded into a `prod-artifacts/` folder). Without `--state`, the selection fails. In dbt Cloud, `--defer` + \"compare to production\" provides that manifest automatically.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#state",
    fr: {
      question: "Que faut-il fournir à dbt pour que `--select state:modified` fonctionne ?",
      choices: [
        "Un dépôt git avec un diff non commité",
        "Un dossier d'artefacts (contenant `manifest.json` d'un run de référence) via `--state <chemin>` ou `DBT_STATE`",
        "Le fichier `run_results.json` du dernier run local",
        "Rien, dbt compare avec `target/` automatiquement",
      ],
      explanation: "`state:modified` compare le manifest courant avec un **manifest de référence** (typiquement celui de la prod, téléchargé dans un dossier `prod-artifacts/`). Sans `--state`, la sélection échoue. En dbt Cloud, `--defer` + « compare to production » fournit ce manifest automatiquement.",
    },
  },
  {
    id: "state-002",
    module: "state",
    topic: "Defer",
    topic_fr: "Defer",
    question: "What does the `--defer` flag do?",
    choices: [
      "It postpones model execution to the end of the run",
      "For any `ref()` to a model that is **not selected and missing** from the current environment, it resolves the reference to the relation of the `--state` environment",
      "It runs the tests first, then the models",
      "It ignores unmodified models",
    ],
    answer: [1],
    explanation: "With `--defer --state prod-artifacts`, if `fct_orders` references `stg_orders` but `stg_orders` is neither selected nor present in the dev schema, dbt reads `stg_orders` **from prod** (the relation in the reference manifest). This avoids rebuilding all upstream in CI or dev. `--favor-state` forces the state version even if the object exists locally.",
    source: "https://docs.getdbt.com/reference/node-selection/defer",
    fr: {
      question: "Que fait le flag `--defer` ?",
      choices: [
        "Il reporte l'exécution des modèles à la fin du run",
        "Pour tout `ref()` vers un modèle **non sélectionné et absent** de l'environnement courant, il résout la référence vers la relation de l'environnement de `--state`",
        "Il exécute d'abord les tests, puis les modèles",
        "Il ignore les modèles non modifiés",
      ],
      explanation: "Avec `--defer --state prod-artifacts`, si `fct_orders` référence `stg_orders` mais que `stg_orders` n'est ni sélectionné ni présent dans le schéma de dev, dbt lit `stg_orders` **en prod** (relation du manifest de référence). Cela évite de reconstruire tout l'amont en CI ou en dev. `--favor-state` force la version de state même si l'objet existe localement.",
    },
  },
  {
    id: "state-003",
    module: "state",
    topic: "Slim CI",
    topic_fr: "Slim CI",
    question: "Which command implements a \"Slim CI\": build and test only what changed and what depends on it, reading upstream from production?",
    choices: [
      "`dbt build --select state:modified+ --defer --state prod-artifacts`",
      "`dbt build --select +state:modified --full-refresh`",
      "`dbt run --select modified`",
      "`dbt build --defer` alone",
    ],
    answer: [0],
    explanation: "`state:modified+` = modified nodes and their descendants (to check nothing breaks downstream). `--defer --state` points unselected `ref`s to prod. `dbt build` includes tests. This is exactly the pattern of this repo's `feature/slim-ci` workflow.",
    source: "https://docs.getdbt.com/docs/deploy/continuous-integration",
    fr: {
      question: "Quelle commande implémente un « Slim CI » : construire et tester uniquement ce qui a changé et ce qui en dépend, en lisant l'amont depuis la prod ?",
      choices: [
        "`dbt build --select state:modified+ --defer --state prod-artifacts`",
        "`dbt build --select +state:modified --full-refresh`",
        "`dbt run --select modified`",
        "`dbt build --defer` seul",
      ],
      explanation: "`state:modified+` = nœuds modifiés et leurs descendants (pour vérifier qu'on ne casse rien en aval). `--defer --state` fait pointer les `ref` non sélectionnés vers la prod. `dbt build` inclut les tests. C'est exactement le pattern du workflow `feature/slim-ci` de ce repo.",
    },
  },
  {
    id: "state-004",
    module: "state",
    topic: "dbt clone",
    topic_fr: "dbt clone",
    question: "What does `dbt clone --select state:modified+ --state prod-artifacts` do?",
    choices: [
      "It copies the code of the modified models into a new folder",
      "It creates in the target schema **clones** (zero-copy on Snowflake) of the state environment's relations for the selected nodes",
      "It exports the data as CSV",
      "It duplicates the manifest",
    ],
    answer: [1],
    explanation: "`dbt clone` (1.6+) creates copies of objects from another environment — via `create table … clone` on Snowflake (instant, no initial storage cost), or via views pointing to the source elsewhere. Use cases: quickly populate a dev/staging environment, or a blue/green deployment.",
    source: "https://docs.getdbt.com/reference/commands/clone",
    fr: {
      question: "Que fait `dbt clone --select state:modified+ --state prod-artifacts` ?",
      choices: [
        "Il copie le code des modèles modifiés dans un nouveau dossier",
        "Il crée dans le schéma cible des **clones** (zero-copy sur Snowflake) des relations de l'environnement de state pour les nœuds sélectionnés",
        "Il exporte les données en CSV",
        "Il duplique le manifest",
      ],
      explanation: "`dbt clone` (1.6+) crée des copies des objets d'un autre environnement — via `create table … clone` sur Snowflake (instantané, sans coût de stockage initial), ou via des vues pointant sur la source ailleurs. Cas d'usage : peupler rapidement un environnement de dev/staging ou un déploiement blue/green.",
    },
  },
  {
    id: "state-005",
    module: "state",
    topic: "result:",
    topic_fr: "result:",
    question: "After a `dbt build` where some models failed, how do you re-run only the errored nodes **and their descendants**?",
    choices: [
      "`dbt build --select result:error+ --state target/`",
      "`dbt build --select state:modified+`",
      "`dbt retry --downstream`",
      "`dbt build --select failed+`",
    ],
    answer: [0],
    explanation: "The `result:` method (`error`, `fail`, `warn`, `pass`, `skipped`, `success`) reads `run_results.json` from the `--state` folder. `result:error+` selects errored nodes and their descendants. `dbt retry` does something close but has no `--downstream` option; it resumes the error/fail/skipped nodes as they are.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#result",
    fr: {
      question: "Après un `dbt build` où certains modèles ont échoué, comment relancer uniquement les nœuds en erreur **et leurs descendants** ?",
      choices: [
        "`dbt build --select result:error+ --state target/`",
        "`dbt build --select state:modified+`",
        "`dbt retry --downstream`",
        "`dbt build --select failed+`",
      ],
      explanation: "La méthode `result:` (`error`, `fail`, `warn`, `pass`, `skipped`, `success`) lit `run_results.json` du dossier `--state`. `result:error+` sélectionne les nœuds en erreur et leurs descendants. `dbt retry` fait quelque chose de proche mais sans option `--downstream` ; il reprend les nœuds error/fail/skipped tels quels.",
    },
  },
  {
    id: "state-006",
    module: "state",
    topic: "state:modified",
    topic_fr: "state:modified",
    question: "You want to select only the models whose **SQL** changed, ignoring description or config changes. Which sub-selector do you use?",
    choices: ["state:modified.body", "state:modified.configs", "state:modified.contract", "state:new"],
    answer: [0],
    explanation: "`state:modified` has sub-selectors: `.body` (SQL/Python content), `.configs`, `.relation` (database/schema/alias), `.persisted_descriptions`, `.macros` (a used macro changed), `.contract`. `state:new` = node absent from the reference manifest. `state:unmodified` also exists.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#state",
    fr: {
      question: "Vous voulez sélectionner uniquement les modèles dont le **SQL** a changé, en ignorant les changements de description ou de config. Quel sous-sélecteur utiliser ?",
      choices: ["state:modified.body", "state:modified.configs", "state:modified.contract", "state:new"],
      explanation: "`state:modified` se décline en sous-sélecteurs : `.body` (contenu SQL/Python), `.configs`, `.relation` (database/schema/alias), `.persisted_descriptions`, `.macros` (macro utilisée modifiée), `.contract`. `state:new` = nœud absent du manifest de référence. `state:unmodified` existe aussi.",
    },
  },
  {
    id: "state-007",
    module: "state",
    topic: "source_status",
    topic_fr: "source_status",
    question: "How do you rebuild only the models whose sources received **new data** since the last freshness check?",
    choices: [
      "`dbt build --select state:modified+`",
      "`dbt source freshness` then `dbt build --select source_status:fresher+ --state <previous artifacts>`",
      "`dbt build --select source:*+ --fresh`",
      "`dbt run --select tag:fresh`",
    ],
    answer: [1],
    explanation: "`source_status:fresher` compares the current `sources.json` with the one in the `--state` folder and selects sources whose `max_loaded_at` advanced. With `+`, their descendants are rebuilt. This enables \"only if new data\" incremental jobs.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#source_status",
    fr: {
      question: "Comment ne reconstruire que les modèles dont les sources ont reçu de **nouvelles données** depuis le dernier check de fraîcheur ?",
      choices: [
        "`dbt build --select state:modified+`",
        "`dbt source freshness` puis `dbt build --select source_status:fresher+ --state <artefacts précédents>`",
        "`dbt build --select source:*+ --fresh`",
        "`dbt run --select tag:fresh`",
      ],
      explanation: "`source_status:fresher` compare le `sources.json` courant avec celui du dossier `--state` et sélectionne les sources dont `max_loaded_at` a avancé. Avec `+`, on rebâtit leurs descendants. Ça permet des jobs incrémentaux « seulement si nouvelles données ».",
    },
  },
]);
