// Module : Exploiter le state dbt (state:modified, defer, clone, result:)
QuizBank.add([
  {
    id: "state-001",
    module: "state",
    topic: "state:modified",
    question: "Que faut-il fournir à dbt pour que `--select state:modified` fonctionne ?",
    choices: [
      "Un dépôt git avec un diff non commité",
      "Un dossier d'artefacts (contenant `manifest.json` d'un run de référence) via `--state <chemin>` ou `DBT_STATE`",
      "Le fichier `run_results.json` du dernier run local",
      "Rien, dbt compare avec `target/` automatiquement",
    ],
    answer: [1],
    explanation: "`state:modified` compare le manifest courant avec un **manifest de référence** (typiquement celui de la prod, téléchargé dans un dossier `prod-artifacts/`). Sans `--state`, la sélection échoue. En dbt Cloud, `--defer` + « compare to production » fournit ce manifest automatiquement.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#state",
  },
  {
    id: "state-002",
    module: "state",
    topic: "Defer",
    question: "Que fait le flag `--defer` ?",
    choices: [
      "Il reporte l'exécution des modèles à la fin du run",
      "Pour tout `ref()` vers un modèle **non sélectionné et absent** de l'environnement courant, il résout la référence vers la relation de l'environnement de `--state`",
      "Il exécute d'abord les tests, puis les modèles",
      "Il ignore les modèles non modifiés",
    ],
    answer: [1],
    explanation: "Avec `--defer --state prod-artifacts`, si `fct_orders` référence `stg_orders` mais que `stg_orders` n'est ni sélectionné ni présent dans le schéma de dev, dbt lit `stg_orders` **en prod** (relation du manifest de référence). Cela évite de reconstruire tout l'amont en CI ou en dev. `--favor-state` force la version de state même si l'objet existe localement.",
    source: "https://docs.getdbt.com/reference/node-selection/defer",
  },
  {
    id: "state-003",
    module: "state",
    topic: "Slim CI",
    question: "Quelle commande implémente un « Slim CI » : construire et tester uniquement ce qui a changé et ce qui en dépend, en lisant l'amont depuis la prod ?",
    choices: [
      "`dbt build --select state:modified+ --defer --state prod-artifacts`",
      "`dbt build --select +state:modified --full-refresh`",
      "`dbt run --select modified`",
      "`dbt build --defer` seul",
    ],
    answer: [0],
    explanation: "`state:modified+` = nœuds modifiés et leurs descendants (pour vérifier qu'on ne casse rien en aval). `--defer --state` fait pointer les `ref` non sélectionnés vers la prod. `dbt build` inclut les tests. C'est exactement le pattern du workflow `feature/slim-ci` de ce repo.",
    source: "https://docs.getdbt.com/docs/deploy/continuous-integration",
  },
  {
    id: "state-004",
    module: "state",
    topic: "dbt clone",
    question: "Que fait `dbt clone --select state:modified+ --state prod-artifacts` ?",
    choices: [
      "Il copie le code des modèles modifiés dans un nouveau dossier",
      "Il crée dans le schéma cible des **clones** (zero-copy sur Snowflake) des relations de l'environnement de state pour les nœuds sélectionnés",
      "Il exporte les données en CSV",
      "Il duplique le manifest",
    ],
    answer: [1],
    explanation: "`dbt clone` (1.6+) crée des copies des objets d'un autre environnement — via `create table … clone` sur Snowflake (instantané, sans coût de stockage initial), ou via des vues pointant sur la source ailleurs. Cas d'usage : peupler rapidement un environnement de dev/staging ou un déploiement blue/green.",
    source: "https://docs.getdbt.com/reference/commands/clone",
  },
  {
    id: "state-005",
    module: "state",
    topic: "result:",
    question: "Après un `dbt build` où certains modèles ont échoué, comment relancer uniquement les nœuds en erreur **et leurs descendants** ?",
    choices: [
      "`dbt build --select result:error+ --state target/`",
      "`dbt build --select state:modified+`",
      "`dbt retry --downstream`",
      "`dbt build --select failed+`",
    ],
    answer: [0],
    explanation: "La méthode `result:` (`error`, `fail`, `warn`, `pass`, `skipped`, `success`) lit `run_results.json` du dossier `--state`. `result:error+` sélectionne les nœuds en erreur et leurs descendants. `dbt retry` fait quelque chose de proche mais sans option `--downstream` ; il reprend les nœuds error/fail/skipped tels quels.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#result",
  },
  {
    id: "state-006",
    module: "state",
    topic: "state:modified",
    question: "Vous voulez sélectionner uniquement les modèles dont le **SQL** a changé, en ignorant les changements de description ou de config. Quel sous-sélecteur utiliser ?",
    choices: ["state:modified.body", "state:modified.configs", "state:modified.contract", "state:new"],
    answer: [0],
    explanation: "`state:modified` se décline en sous-sélecteurs : `.body` (contenu SQL/Python), `.configs`, `.relation` (database/schema/alias), `.persisted_descriptions`, `.macros` (macro utilisée modifiée), `.contract`. `state:new` = nœud absent du manifest de référence. `state:unmodified` existe aussi.",
    source: "https://docs.getdbt.com/reference/node-selection/methods#state",
  },
  {
    id: "state-007",
    module: "state",
    topic: "source_status",
    question: "Comment ne reconstruire que les modèles dont les sources ont reçu de **nouvelles données** depuis le dernier check de fraîcheur ?",
    choices: [
      "`dbt build --select state:modified+`",
      "`dbt source freshness` puis `dbt build --select source_status:fresher+ --state <artefacts précédents>`",
      "`dbt build --select source:*+ --fresh`",
      "`dbt run --select tag:fresh`",
    ],
    answer: [1],
    explanation: "`source_status:fresher` compare le `sources.json` courant avec celui du dossier `--state` et sélectionne les sources dont `max_loaded_at` a avancé. Avec `+`, on rebâtit leurs descendants. Ça permet des jobs incrémentaux « seulement si nouvelles données ».",
    source: "https://docs.getdbt.com/reference/node-selection/methods#source_status",
  },
]);
