version: 2

sources:
  - name: eth
    description: This is my eth source
    database: eth
    schema: eth_schema
    tables:
      - name: contracts
        description: This is my contracts table
      - name: token_transfers
      - name: transactions 
        columns:
          - name: hash
            data_tests:
              - not_null
              - unique
